<<<<<<< HEAD
title: My_IBI1_personal_homepage
=======
title: Jekyll-My_IBI1_personal_homepage
>>>>>>> 349af8575794efdfb8a736e4e73968f2a0bdb927
theme: hacker
description: IBI1 2025-26 Course Git practical personal website
